apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-y8ps
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-y8ps@sha256:a0bf844c9feea5e85afdb7626490e952ee58d0ed3a8e45f724db5f7478766ca4
        name: my-nodejs
        resources: {}
status: {}
